version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    extra_hosts:
      - "db.uxcsziylmyogvcqyyuiw.supabase.co:65.9.91.24"

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend