/**
 * Объект с прямыми публичными URL ко всем SVG-иконкам.
 * Путь скорректирован согласно структуре: /public/images/icons/
 */
export const iconPaths = {
  alertHexa: '/images/icons/alert-hexa.svg',
  alert: '/images/icons/alert.svg',
  angleDown: '/images/icons/angle-down.svg',
  angleLeft: '/images/icons/angle-left.svg',
  angleRight: '/images/icons/angle-right.svg',
  angleUp: '/images/icons/angle-up.svg',
  arrowDown: '/images/icons/arrow-down.svg',
  arrowRight: '/images/icons/arrow-right.svg',
  arrowUp: '/images/icons/arrow-up.svg',
  audio: '/images/icons/audio.svg',
  bolt: '/images/icons/bolt.svg',
  boxCube: '/images/icons/box-cube.svg',
  boxLine: '/images/icons/box-line.svg',
  box: '/images/icons/box.svg',
  calendar: '/images/icons/calendar.svg',
  calenderLine: '/images/icons/calender-line.svg',
  chat: '/images/icons/chat.svg',
  checkCircle: '/images/icons/check-circle.svg',
  checkLine: '/images/icons/check-line.svg',
  chevronDown: '/images/icons/chevron-down.svg',
  chevronLeft: '/images/icons/chevron-left.svg',
  chevronUp: '/images/icons/chevron-up.svg',
  closeLine: '/images/icons/close-line.svg',
  close: '/images/icons/close.svg',
  copy: '/images/icons/copy.svg',
  docs: '/images/icons/docs.svg',
  dollarLine: '/images/icons/dollar-line.svg',
  download: '/images/icons/download.svg',
  envelope: '/images/icons/envelope.svg',
  eyeClose: '/images/icons/eye-close.svg',
  eye: '/images/icons/eye.svg',
  fileImageDark: '/images/icons/file-image-dark.svg',
  fileImage: '/images/icons/file-image.svg',
  filePdfDark: '/images/icons/file-pdf-dark.svg',
  filePdf: '/images/icons/file-pdf.svg',
  fileVideoDark: '/images/icons/file-video-dark.svg',
  fileVideo: '/images/icons/file-video.svg',
  file: '/images/icons/file.svg',
  folder: '/images/icons/folder.svg',
  grid: '/images/icons/grid.svg',
  group: '/images/icons/group.svg',
  horizontalDots: '/images/icons/horizontal-dots.svg',
  infoError: '/images/icons/info-error.svg',
  infoHexa: '/images/icons/info-hexa.svg',
  info: '/images/icons/info.svg',
  list: '/images/icons/list.svg',
  lock: '/images/icons/lock.svg',
  mailLine: '/images/icons/mail-line.svg',
  moredot: '/images/icons/moredot.svg',
  page: '/images/icons/page.svg',
  paperPlane: '/images/icons/paper-plane.svg',
  pencil: '/images/icons/pencil.svg',
  pieChart: '/images/icons/pie-chart.svg',
  plugIn: '/images/icons/plug-in.svg',
  plus: '/images/icons/plus.svg',
  shootingStar: '/images/icons/shooting-star.svg',
  table: '/images/icons/table.svg',
  taskIcon: '/images/icons/task-icon.svg',
  time: '/images/icons/time.svg',
  trash: '/images/icons/trash.svg',
  userCircle: '/images/icons/user-circle.svg',
  userLine: '/images/icons/user-line.svg',
  videos: '/images/icons/videos.svg',
};

export type IconName = keyof typeof iconPaths;