/**
 * Объект с прямыми публичными URL ко всем SVG-иконкам.
 * Путь скорректирован согласно структуре: /public/images/icons/
 */
export const ICONS = {
  // --- icons ---
  ALERT_HEXA: '/images/icons/alert-hexa.svg',
  ALERT: '/images/icons/alert.svg',
  ANGLE_DOWN: '/images/icons/angle-down.svg',
  ANGLE_LEFT: '/images/icons/angle-left.svg',
  ANGLE_RIGHT: '/images/icons/angle-right.svg',
  ANGLE_UP: '/images/icons/angle-up.svg',
  ARROW_DOWN: '/images/icons/arrow-down.svg',
  ARROW_RIGHT: '/images/icons/arrow-right.svg',
  ARROW_UP: '/images/icons/arrow-up.svg',
  AUDIO: '/images/icons/audio.svg',
  BOLT: '/images/icons/bolt.svg',
  BOX_CUBE: '/images/icons/box-cube.svg',
  BOX_LINE: '/images/icons/box-line.svg',
  BOX: '/images/icons/box.svg',
  CALENDAR: '/images/icons/calendar.svg',
  CALENDER_LINE: '/images/icons/calender-line.svg',
  CHAT: '/images/icons/chat.svg',
  CHECK_CIRCLE: '/images/icons/check-circle.svg',
  CHECK_LINE: '/images/icons/check-line.svg',
  CHEVRON_DOWN: '/images/icons/chevron-down.svg',
  CHEVRON_LEFT: '/images/icons/chevron-left.svg',
  CHEVRON_UP: '/images/icons/chevron-up.svg',
  CLOSE_LINE: '/images/icons/close-line.svg',
  CLOSE: '/images/icons/close.svg',
  COPY: '/images/icons/copy.svg',
  DOCS: '/images/icons/docs.svg',
  DOLLAR_LINE: '/images/icons/dollar-line.svg',
  DOWNLOAD: '/images/icons/download.svg',
  ENVELOPE: '/images/icons/envelope.svg',
  EYE_CLOSE: '/images/icons/eye-close.svg',
  EYE: '/images/icons/eye.svg',
  FILE_IMAGE_DARK: '/images/icons/file-image-dark.svg',
  FILE_IMAGE: '/images/icons/file-image.svg',
  FILE_PDF_DARK: '/images/icons/file-pdf-dark.svg',
  FILE_PDF: '/images/icons/file-pdf.svg',
  FILE_VIDEO_DARK: '/images/icons/file-video-dark.svg',
  FILE_VIDEO: '/images/icons/file-video.svg',
  FILE: '/images/icons/file.svg',
  FOLDER: '/images/icons/folder.svg',
  GRID: '/images/icons/grid.svg',
  GROUP: '/images/icons/group.svg',
  HORIZONTAL_DOTS: '/images/icons/horizontal-dots.svg',
  INFO_ERROR: '/images/icons/info-error.svg',
  INFO_HEXA: '/images/icons/info-hexa.svg',
  INFO: '/images/icons/info.svg',
  LIST: '/images/icons/list.svg',
  LOCK: '/images/icons/lock.svg',
  MAIL_LINE: '/images/icons/mail-line.svg',
  MOREDOT: '/images/icons/moredot.svg',
  PAGE: '/images/icons/page.svg',
  PAPER_PLANE: '/images/icons/paper-plane.svg',
  PENCIL: '/images/icons/pencil.svg',
  PIE_CHART: '/images/icons/pie-chart.svg',
  PLUG_IN: '/images/icons/plug-in.svg',
  PLUS: '/images/icons/plus.svg',
  SHOOTING_STAR: '/images/icons/shooting-star.svg',
  TABLE: '/images/icons/table.svg',
  TASK_ICON: '/images/icons/task-icon.svg',
  TIME: '/images/icons/time.svg',
  TRASH: '/images/icons/trash.svg',
  USER_CIRCLE: '/images/icons/user-circle.svg',
  USER_LINE: '/images/icons/user-line.svg',
  VIDEOS: '/images/icons/videos.svg',

  // --- shape ---
  GRID_01: '/images/shape/grid-01.svg',

  // --- logo ---
  LOGO: '/images/logo/logo.svg',
  LOGO_DARK: '/images/logo/logo-dark.svg',
  LOGO_ICON: '/images/logo/logo-icon.svg',
  AUTH_LOGO: '/images/logo/auth-logo.svg',

  // --- brand ---
  BRAND_01: '/images/brand/brand-01.svg',
  BRAND_02: '/images/brand/brand-02.svg',
  BRAND_03: '/images/brand/brand-03.svg',
  BRAND_04: '/images/brand/brand-04.svg',
  BRAND_05: '/images/brand/brand-05.svg',
  BRAND_06: '/images/brand/brand-06.svg',
  BRAND_07: '/images/brand/brand-07.svg',
  BRAND_08: '/images/brand/brand-08.svg',
  BRAND_09: '/images/brand/brand-09.svg',
  BRAND_10: '/images/brand/brand-10.svg',
  BRAND_11: '/images/brand/brand-11.svg',
  BRAND_12: '/images/brand/brand-12.svg',
  BRAND_13: '/images/brand/brand-13.svg',
  BRAND_14: '/images/brand/brand-14.svg',
  BRAND_15: '/images/brand/brand-15.svg',

  // --- error ---
  ERROR_404: '/images/error/404.svg',
  ERROR_404_DARK: '/images/error/404-dark.svg',
  ERROR_500: '/images/error/500.svg',
  ERROR_500_DARK: '/images/error/500-dark.svg',
  ERROR_503: '/images/error/503.svg',
  ERROR_503_DARK: '/images/error/503-dark.svg',
  MAINTENANCE: '/images/error/maintenance.svg',
  MAINTENANCE_DARK: '/images/error/maintenance-dark.svg',
  SUCCESS: '/images/error/success.svg',
  SUCCESS_DARK: '/images/error/success-dark.svg',

  // --- country ---
  COUNTRY_01: '/images/country/country-01.svg',
  COUNTRY_02: '/images/country/country-02.svg',
  COUNTRY_03: '/images/country/country-03.svg',
  COUNTRY_04: '/images/country/country-04.svg',
  COUNTRY_05: '/images/country/country-05.svg',
  COUNTRY_06: '/images/country/country-06.svg',
  COUNTRY_07: '/images/country/country-07.svg',
  COUNTRY_08: '/images/country/country-08.svg',

  // --- task ---
  TASK_PDF: '/images/task/pdf.svg',
  TASK_GOOGLE_DRIVE: '/images/task/google-drive.svg',
};

export type IconName = keyof typeof ICONS;