env:
  contexts:
    - name: "API Security Test"
      urls:
        - "http://localhost:3000/api"
      includePaths:
        - "http://localhost:3000/api/.*"
      excludePaths:
        - ".*\\.js"
        - ".*\\.css"
        - ".*\\.png"
        - ".*\\.jpeg"
        - ".*\\.jpg"
        - ".*\\.gif"
        - ".*\\.svg"
      authentication:
        method: "json"
        loginUrl: "http://localhost:3000/api/auth/login"
        loginRequestData: '{"email": "{%username%}", "password": "{%password%}"}'
        loggedInIndicator: '"token":'
        loggedOutIndicator: '"error":'
      users:
        - name: "testuser"
          credentials:
            username: "test@example.com"
            password: "TestPassword123!"
        - name: "admin"
          credentials:
            username: "admin@example.com"
            password: "AdminPass123!"
      sessionManagement:
        method: "httpAuthSessionManagement"
        parameters:
          loginUrl: "http://localhost:3000/api/auth/login"
          
jobs:
  - type: passiveScan-config
    parameters:
      maxAlertsPerRule: 10
      scanOnlyInScope: true
      
  - type: spider
    parameters:
      maxDuration: 10
      maxDepth: 10
      maxChildren: 0
      acceptCookies: true
      handleODataParametersVisited: true
      handleParameters: "USE_ALL"
      maxParseSizeBytes: 5000000
      parseComments: true
      parseGit: false
      parseRobotsTxt: false
      parseSitemapXml: false
      parseSVNEntries: false
      postForm: true
      processForm: true
      requestWaitTime: 200
      sendRefererHeader: true
      threadCount: 5
      userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
      
  - type: spiderAjax
    parameters:
      maxDuration: 10
      maxCrawlDepth: 10
      numberOfBrowsers: 1
      browserId: "chrome-headless"
      clickDefaultElems: true
      clickElemsOnce: true
      eventWait: 1000
      randomInputs: true
      reloadWait: 1000
      
  - type: passiveScan-wait
    parameters:
      maxDuration: 10
      
  - type: activeScan
    parameters:
      maxRuleDurationInMins: 5
      maxScanDurationInMins: 60
      delayInMs: 0
      handleAntiCSRFTokens: true
      injectPluginIdInHeader: true
      scanHeadersAllRequests: true
      threadPerHost: 2
      policy: "API-Test-Policy"
      
  - type: report
    parameters:
      template: "risk-confidence-html"
      reportDir: "security-reports"
      reportFile: "ZAP-Report"
      reportTitle: "API Security Test Report"
      reportDescription: "Automated security scan of the API endpoints"
      displayReport: false
      
policies:
  - name: "API-Test-Policy"
    rules:
      - id: 0  # Directory Browsing
        strength: "HIGH"
        threshold: "MEDIUM"
      - id: 10010  # Cookie No HttpOnly Flag
        strength: "HIGH"
        threshold: "LOW"
      - id: 10011  # Cookie Without Secure Flag
        strength: "HIGH"
        threshold: "LOW"
      - id: 10015  # Incomplete or No Cache-control and Pragma HTTP Header Set
        strength: "HIGH"
        threshold: "LOW"
      - id: 10016  # Web Browser XSS Protection Not Enabled
        strength: "HIGH"
        threshold: "LOW"
      - id: 10017  # Cross-Domain JavaScript Source File Inclusion
        strength: "HIGH"
        threshold: "MEDIUM"
      - id: 10019  # Content-Type Header Missing
        strength: "HIGH"
        threshold: "LOW"
      - id: 10020  # X-Frame-Options Header Not Set
        strength: "HIGH"
        threshold: "MEDIUM"
      - id: 10021  # X-Content-Type-Options Header Missing
        strength: "HIGH"
        threshold: "LOW"
      - id: 10023  # Information Disclosure - Debug Error Messages
        strength: "HIGH"
        threshold: "LOW"
      - id: 10024  # Information Disclosure - Sensitive Information in URL
        strength: "HIGH"
        threshold: "MEDIUM"
      - id: 10025  # Information Disclosure - Sensitive Information in HTTP Referrer Header
        strength: "HIGH"
        threshold: "MEDIUM"
      - id: 10027  # Information Disclosure - Suspicious Comments
        strength: "HIGH"
        threshold: "LOW"
      - id: 10032  # Viewstate Without MAC Signature
        strength: "HIGH"
        threshold: "MEDIUM"
      - id: 10040  # Secure Pages Include Mixed Content
        strength: "HIGH"
        threshold: "MEDIUM"
      - id: 10105  # Weak Authentication Method
        strength: "HIGH"
        threshold: "MEDIUM"
      - id: 10202  # Absence of Anti-CSRF Tokens
        strength: "HIGH"
        threshold: "MEDIUM"
      - id: 40003  # CRLF Injection
        strength: "HIGH"
        threshold: "MEDIUM"
      - id: 40008  # Parameter Tampering
        strength: "HIGH"
        threshold: "MEDIUM"
      - id: 40009  # Server Side Include
        strength: "HIGH"
        threshold: "MEDIUM"
      - id: 40012  # Cross Site Scripting (Reflected)
        strength: "HIGH"
        threshold: "MEDIUM"
      - id: 40013  # Session Fixation
        strength: "HIGH"
        threshold: "MEDIUM"
      - id: 40014  # Cross Site Scripting (Persistent)
        strength: "HIGH"
        threshold: "MEDIUM"
      - id: 40016  # Cross Site Scripting (Persistent) - Prime
        strength: "HIGH"
        threshold: "MEDIUM"
      - id: 40017  # Cross Site Scripting (Persistent) - Spider
        strength: "HIGH"
        threshold: "MEDIUM"
      - id: 40018  # SQL Injection
        strength: "HIGH"
        threshold: "MEDIUM"
      - id: 40019  # SQL Injection - MySQL
        strength: "HIGH"
        threshold: "MEDIUM"
      - id: 40020  # SQL Injection - Hypersonic SQL
        strength: "HIGH"
        threshold: "MEDIUM"
      - id: 40021  # SQL Injection - Oracle
        strength: "HIGH"
        threshold: "MEDIUM"
      - id: 40022  # SQL Injection - PostgreSQL
        strength: "HIGH"
        threshold: "MEDIUM"
      - id: 40023  # Possible Username Enumeration
        strength: "HIGH"
        threshold: "MEDIUM"
      - id: 40024  # SQL Injection - SQLite
        strength: "HIGH"
        threshold: "MEDIUM"
      - id: 40025  # Proxy Disclosure
        strength: "HIGH"
        threshold: "MEDIUM"
      - id: 40026  # Cross Site Scripting (DOM Based)
        strength: "HIGH"
        threshold: "MEDIUM"
      - id: 40027  # SQL Injection - MsSQL
        strength: "HIGH"
        threshold: "MEDIUM"
      - id: 40028  # ELMAH Information Leak
        strength: "HIGH"
        threshold: "MEDIUM"
      - id: 40029  # Trace.axd Information Leak
        strength: "HIGH"
        threshold: "MEDIUM"
      - id: 40032  # .htaccess Information Leak
        strength: "HIGH"
        threshold: "MEDIUM"
      - id: 40034  # .env Information Leak
        strength: "HIGH"
        threshold: "MEDIUM"
      - id: 90001  # Insecure JSF ViewState
        strength: "HIGH"
        threshold: "MEDIUM"
      - id: 90011  # Charset Mismatch
        strength: "HIGH"
        threshold: "LOW"
      - id: 90022  # Application Error Disclosure
        strength: "HIGH"
        threshold: "MEDIUM"
      - id: 90033  # Loosely Scoped Cookie
        strength: "HIGH"
        threshold: "LOW"
        
alertFilters:
  - ruleId: 10015  # Ignore cache headers for API
    alertName: "Incomplete or No Cache-control and Pragma HTTP Header Set"
    url: "http://localhost:3000/api/.*"
    enabled: false
